### ISSUE TITLE
Add a doorbell

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#1]
- [ ] buy doorbell
- [ ] install doorbell

**Comment by jcushman** [comment]
There is a rabbithole here, but basically the question seems to be (1) do you want one receiver or two? (2) do you want one of the receivers to be battery powered instead of requiring a wall socket? (3) how ridiculous do you want the button to look?

A few options:

http://www.amazon.com/Etekcity-Wireless-Doorbell-Plug--Battery-Operated/dp/B010E9GFEG/
http://www.amazon.com/Wireless-Doorbell-Portable-Indicator-Batteries/dp/B0127TSJO0/
http://www.amazon.com/SadoTech-Wireless-Receivers-Operating-Batteries/dp/B00J4FHOB0/
http://www.amazon.com/SadoTech-Wireless-Doorbell-Operating-Batteries/dp/B00FXLGI0W/

I arbitrarily vote for the first one so we can have a second battery-powered receiver near the third floor without worrying about a socket.

**Comment by teresaORM** [comment]
Hmmm, it might turn out that I don't have any opinion between those doorbells. They all seem fine?

My dream might be to have something a little more stylish looking, a la:
http://www.signaturehardware.com/hardware/doorbells/push-button-doorbells.html

But it doesn't seem like doorbells come in both stylish and wireless (and well-reviewed)? Wait, see the comments here:
http://www.apartmenttherapy.com/good-questions-493-101540

This is not a cheap way to do it, but these guys will sell you a fancy doorbell with the converter kit to make it wireless:
http://doorbellfactory.com/

![screen shot 2015-08-30 at 5 50 29 pm](https://cloud.githubusercontent.com/assets/1180804/9569668/ae0c3e28-4f3f-11e5-907a-1d63d90cac76.png)

**Comment by jcushman** [comment]
Ordered http://www.amazon.com/Wireless-Doorbell-Portable-Indicator-Batteries/dp/B0127TSJO0/ for now -- later we can get an awesome one ...
