### ISSUE TITLE
Fix broken window on 3rd floor and in basement

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#10]

**Comment by teresaORM** [comment]
Should we just call a little local place like this?
http://www.baystateglassboston.com/
http://www.yelp.com/biz/shawmut-glass-co-boston-2
http://www.yelp.com/biz/boston-glass-and-boarding-service-dorchester

**Comment by jcushman** [comment]
Sure! Probably something that's easy to quote on the phone -- if the price
isn't too high, we could just go with the first one that answers.

(Basement window might be trickier because it's not upgraded yet?)

**Comment by teresaORM** [comment]
Dude from Shawmut Glass will come take a look (and fix on the spot? unclear?) at 6pm Monday.

**Comment by teresaORM** [comment]
Broken windows theory of house fixing.
![img_5635](https://cloud.githubusercontent.com/assets/1180804/10327244/413b9734-6c73-11e5-85fb-8b8cb57be82d.JPG)
![img_5637](https://cloud.githubusercontent.com/assets/1180804/10327243/41384476-6c73-11e5-8fc0-8c97fd146c56.JPG)

$225 per window, they'll call next week when the replacement insulated panes are in. Also their names seems to be Statewide Glass & Mirror Co. now.

**Comment by teresaORM** [comment]
Call to make appt to fix windows: 617-421-1616.

**Comment by teresaORM** [comment]
His supplier is running a week behind. Thinks he'll have the windows on Wednesday -- will call then to schedule install.

**Comment by teresaORM** [comment]
Called again to check. Guy can maybe come by tonight (after 7pm delivery in Boston) to install. He will call.

**Comment by jcushman** [comment]
![image](https://cloud.githubusercontent.com/assets/376272/10677046/1f85be5a-78d8-11e5-8e53-a81ee27f7ea6.png)
