### ISSUE TITLE
Replace kitchen countertops

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#108]
With beautiful IKEA butcher block?

**Comment by jcushman** [comment]
Countertops purchased ...

**Comment by jcushman** [comment]
![image](https://cloud.githubusercontent.com/assets/376272/13061519/5a6af0ec-d406-11e5-827f-1a4f68c5802f.png)

**Comment by teresaORM** [comment]
Half done
![img_6667](https://cloud.githubusercontent.com/assets/1180804/14404805/f63c4726-fe4c-11e5-880f-23620d3cf36b.JPG)

**Comment by teresaORM** [comment]
All done!

**Comment by teresaORM** [comment]
All done!
