### ISSUE TITLE
Derust top of dryer

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#109]
Sand and put on some of this:
http://www.homedepot.com/p/Rust-Oleum-Specialty-12-oz-Epoxy-Gloss-White-Appliance-Spray-Paint-7881830/202056394

**Comment by teresaORM** [comment]
Before
![image](https://cloud.githubusercontent.com/assets/1180804/11316357/52e7c7aa-8fd2-11e5-8656-c5659c27969d.jpg)

After
![image](https://cloud.githubusercontent.com/assets/1180804/11316358/61cba9d0-8fd2-11e5-9074-ef27f5a6751b.jpg)

**Comment by jcushman** [comment]
Such fancy!

**Comment by teresaORM** [comment]
Also I turned the dryer upside down?
