### ISSUE TITLE
Fix screens

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#11]
- [x] front door
- [x] back door

**Comment by teresaORM** [comment]
![img_5489](https://cloud.githubusercontent.com/assets/1180804/9837049/de44a92a-59ff-11e5-91f9-7295f8a4d90d.JPG)

![img_5494](https://cloud.githubusercontent.com/assets/1180804/9837050/de4281cc-59ff-11e5-9f95-4ae2c43323e9.JPG)

![img_5486](https://cloud.githubusercontent.com/assets/1180804/9837047/de42382a-59ff-11e5-85c1-c01c98813408.JPG)

![img_5488](https://cloud.githubusercontent.com/assets/1180804/9837048/de4314fc-59ff-11e5-9ef5-1d04d6d06e45.JPG)
