### ISSUE TITLE
Prepare for Alexes visit

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#110]
- [ ] veganize/deallergify things
- [ ] launder Dropbox apparel
- [ ] locate ice cream shops
- [ ] nerd it up

**Comment by phoenixy1** [comment]
Alex is just vegetarian and is now only allergic to soy, sesame, carrot, nuts, and peanuts!

Also, what would you say your hoodie size is?

**Comment by phoenixy1** [comment]
Oh, also, do you prefer hoodies with or without sleeves?  The hoodie is very warm, if that helps you decide.

**Comment by teresaORM** [comment]
Oh, right! We will put you in the onion room, then.

Um, probably a medium in a hoodie? With sleeves, obvi. (Do you people come from a place with no winter? :snowflake::snowflake::snowflake:)

**Comment by teresaORM** [comment]
http://www.yelp.com/search?find_desc=ice+cream&find_loc=02124&ns=1

**Comment by phoenixy1** [comment]
I was all about the sleeves at first, but the hoodies are really warm, so I
ended up being jealous of the person who got the vest-style -- much more
compatible with SF weather.
They say that the hoodies run large, so I wonder if you might be an S?  M
is 40-34-40, S is 36-30--36.  Does that change your answer at all?

**Comment by phoenixy1** [comment]
ping (+adding your actual email address instead of github)

**Comment by teresaORM** [comment]
Ooops, sorry! We were traveling over the (extended) weekend and hence took a vacation from the issue tracker. I think you're right, probably S, still voting for sleeves. :cow:

**Comment by teresaORM** [comment]
Closing for now. Reopen if new allergies or queries surface!
