### ISSUE TITLE
Fix or replace washing machine

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#26]
Nothing lights up/doesn't start. 

Model is this one or similar:
http://products.geappliances.com/ApplProducts/Dispatcher?REQUEST=SpecPage&Sku=WCRD2050DWC

**Comment by teresaORM** [comment]
Re: new/replacement washers:

Sweethome's best washers and dryers. They feel *very* strongly that you want a front-loader, not a top-loader. Their recs are all about $1000.
http://thesweethome.com/reviews/the-best-washer-and-dryer/

We could maybe try the Habitat for Humanity ReStore:
http://habitatbostonrestore.org/shop.html

My Whirlpool discount is good until about September 12. I saw some top-loaders as low as $300; front-loaders as low as $600.

This guy in Framingham advertises a bunch of used washers ($150-300ish) on Craigslist and people are pretty excited about them. They deliver:
http://www.yelp.com/biz/normans-used-appliances-framingham

There are a million billion washer/dryer sets people are trying to unload on Craigslist, many very cheaply. Probably you would need to pick them up.

**Comment by jcushman** [comment]
Messing around with this cost calculator for washers:

http://michaelbluejay.com/electricity/laundry.html

(Here's my utility cost settings:

![image](https://cloud.githubusercontent.com/assets/376272/9579152/4e717152-4fbe-11e5-980c-c80b0b6f6f27.png)
)

The big factor is how many loads we need per week. If the front-loader needs 1 load per week and the top-loader needs 2 or 3, then we save $65-$130 per year and the front-loader pays for itself in a few years. If they both need the same number of loads, then we save more like $25-$50 year and I'm more inclined to get the cheapest new option from Whirlpool and reevaluate in a few years.

**Comment by jcushman** [comment]
Also that site says you can wash your own clothes with a 5-gallon bucket and a plunger: http://www.off-grid.net/water/diy-washing-machine-and-homemade-laundry-soap/

**Comment by teresaORM** [comment]
Didn't the Sweethome article say that washers are so efficient that everyone -- even the super-energy-conscious tree-hugging-TED-talkers -- uses a washing machine?

**Comment by teresaORM** [comment]
Also, there's just the big-box stores. Like Best Buy is having a Labor Day Sale:

UP TO 30% OFF MAJOR APPLIANCE TOP DEALS
Plus free delivery, haul-away and recycling on major appliance purchases $399 and up.
http://www.bestbuy.com/site/home-appliances/washers-dryers/abcat0910000.c?id=abcat0910000

I'll try pricing out some options tonight. A lot might hinge on delivery/installation charges at the low end.

**Comment by teresaORM** [comment]
Per Whirlpool site, low-end top loaders are about 3.5 cubic feet capacity. Low-end front loaders are either 2.0 cubic feet (compact) or 4.2 cubic feet. So it's not obvious to me that we save a lot of loads with the front loader.

Soooo, cheapest new top-loader looks like Whirlpool's Amana NTW4605EW
http://www.amana.com/laundry/washers/amana__174_3_5_cu__ft__top_load_washer_with_porcelain_tub_ntw4605ew.pro

Reviews seem generally quite good; some people complain that it's noisy.

Home Depot has it for $299 (on sale until 9/12), includes delivery and hookup, plus $22 for hoses and $15 to haul away old one ($336). Earliest delivery is 9/8.
http://www.homedepot.com/p/Amana-3-5-cu-ft-High-Efficiency-Top-Load-Washer-in-White-NTW4605EW/205951120

Best Buy also has it for $299 (on sale), plus $70 for delivery, hookup, and haul away, plus $30 for hoses ($399). Earliest delivery is 9/7.

Direct option is $269, plus $45 for delivery, installation, and hoses, plus $10 for haul away ($324). Earliest delivery is 9/4.

If you are good with this one, I might go with Home Depot for ease of ordering.

**Comment by teresaORM** [comment]
Ordered! I requested delivery on 9/12 (earliest available was 9/10). They'll call the day before with a four-hour delivery window.

Here's the delivery/installation info: http://www.homedepot.com/c/Appliance_Delivery_Installation

**Comment by teresaORM** [comment]
Delivery window is 10:45am-2:45pm, driver will call 30min. before arrival.
