### ISSUE TITLE
Back bedroom has no three-prong outlets

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#28]
Have an electrician add one?

**Comment by jcushman** [comment]
Check two-prong outlets for grounded box.

**Comment by jcushman** [comment]
Confirmed that a couple of our two-prong outlets have grounded boxes -- let's buy half a dozen three-prong outlets and try upgrading?

**Comment by jcushman** [comment]
To buy: 8-inch grounding pigtails

**Comment by teresaORM** [comment]
Yay fixed!
