### ISSUE TITLE
Reattach finials

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#3]

**Comment by teresaORM** [comment]
It seems like they generally screw into a finial base? I'm not sure we have that:
http://www.homedepot.com/p/Unbranded-4-in-x-4-in-Flat-Finial-Base-6-Pack-189299/205112984

(Replacement wood fInials to oogle: http://www.architecturaldepot.com/stair-finials.html)

**Comment by jcushman** [comment]
So attached now!
