### ISSUE TITLE
Curtains for bedroom

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#34]
And elsewhere?

**Comment by teresaORM** [comment]
Like these?
http://m.ikea.com/us/en/catalog/products/art/90232331/
http://m.ikea.com/us/en/catalog/products/art/90111980/

**Comment by jcushman** [comment]
+1. Let's do it!

**Comment by teresaORM** [comment]
Current bedroom rod to window sill is 72"; to floor is 94". So at 98", these will require hemming.

(IKEA shipping is $10 on these $9 curtains and takes a week and a half. So instead, I paid double the price for the curtains on Amazon with free shipping and they'll be here Sunday. If we decide we want a bunch of these, it might be worth actually making an IKEA trip. Or there's a lot of ten on Ebay ...)

**Comment by teresaORM** [comment]
Oops, too sheer! We probably need to go to Bed Bath & Beyond or Target and look at some options in person.

**Comment by mels630** [comment]
We have Matilda (http://www.ikea.com/us/en/catalog/products/10111984/) under and Lenda (http://www.ikea.com/us/en/catalog/products/30090117/) over. And Nina does know these names off the top of her head.

**Comment by teresaORM** [comment]
She seemed like a gal who knows her curtains. Thanks!

**Comment by teresaORM** [comment]
OK, ordered a Matilda to try.
