### ISSUE TITLE
Throw big house party

### ISSUE THREAD

**Issue by abziegler** [jcushman/house#35]

**Comment by teresaORM** [comment]
Ready for QA, @abziegler, @leppert: http://goo.gl/forms/l3kIoDYdQl

**Comment by leppert** [comment]
@teresaORM @jcushman Sad I'll have to miss it. Please let me know the next time you're opening up the digs!

**Comment by teresaORM** [comment]
Success!

![img_6118](https://cloud.githubusercontent.com/assets/1180804/11645498/f8da6372-9d22-11e5-86e0-fe97bc4ef685.JPG)

![img_6108](https://cloud.githubusercontent.com/assets/1180804/11645497/f8d96f58-9d22-11e5-9fb0-3e388e8daf88.JPG)

![img_6107](https://cloud.githubusercontent.com/assets/1180804/11645499/f8db458a-9d22-11e5-838f-463bb183836c.JPG)

![img_6097](https://cloud.githubusercontent.com/assets/1180804/11645496/f8d93c18-9d22-11e5-89a1-94e773010b5a.JPG)
