### ISSUE TITLE
Tree trimming

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#37]
Have overhanging trees trimmed back. Call Eversource? Or a real arborist?

**Comment by jcushman** [comment]
- [Specialized Rigging & Tree Care](http://my.angieslist.com/AngiesList/myangie/checkthelist/spinformation.aspx?6weq8IepK%2b3iKMnGBISX7ZY7RvfKlB12R2dFABfdWWqVHnVJjq%2fiUjB88dTdq4a5VR1M5xfVLQUfuRZjochWB30P1aJFs%2bId3emZr1kBJopFg6coSpp27z7FZ%2fPAbQqkZTSLaWMbVcrcdKp691B%2f4cQidMP4op8NI0lcayLOcDk%3d#r11011702) - left info with guy, said he would call back to schedule
- [Bogan Tree Service](http://my.angieslist.com/AngiesList/myangie/checkthelist/spinformation.aspx?%2fyGJtJYaT8tCsIzpeB4kODwJU2wbOqWUAc0ShKUkOyOlVL9pwL4gBg%2fKJlRaS9XGOZECYDmiopoNuqO872kgLqDp%2fiGOFcBccFBmZxy1x8aNDgQTjnIiexPnRKxQHe6TDRbQGLzKpug2T1vaDHIA%2bcUB8Il2ziuFS16RGCecvs4%3d#r11194207) - left phone message
- [ASC Tree Service](http://my.angieslist.com/AngiesList/myangie/checkthelist/spinformation.aspx?j9vh%2fQ0a%2bNcAXH%2bM1KV4HbxNJzqrVGgrzL8w99C7yxySehs683aoPwK9Gqm1kb9X3ox2AQ0N7OHjsNSljIOlAvMqB49q65yqmkdtYZ8icjFzHdo5mX1fyZ2pi2hOsTBTNdOl%2fEkNVOHPmeScj7Rx%2b%2frfSFXHSwquIHmFEV0sVDQ%3d) - sent Angie's List message

**Comment by jcushman** [comment]
- [Maltby & Co Inc](http://my.angieslist.com/AngiesList/myangie/checkthelist/spinformation.aspx?DyPbB6w0CoJ0GkrCAnYMmIy02k2lBxO+9CH2aiHkT1efmDOQXjgvCUOr6Dj9RL+q2gzHqs/soepuXmyNW9bB/8imyxWJ/vidBzRtYW2h7JmmPiQlbSQn5nYUjeRlwdPL) - left message 9/28, lady said guy would call back
- [Arborway Tree Care Inc](http://my.angieslist.com/AngiesList/myangie/checkthelist/spinformation.aspx?AJvuKR82It7gsftIgv1GNLaHU72fwkQVnlH4DudJqtCfGsxdY5P1PYjokwQ3gqy1RrBgNlUelA4PWTdfiZuBZt%2fWcyKxH4SCWiGDgn01vkfU4vr8z4ukrqVZ6Vaaa0Z8NJeZ7NzT%2bHx7AqBsmxe7hy4ttE4Ca1UNQpLvZcISuzA%3d) - scheduled for 9/30 9AM

**Comment by jcushman** [comment]
Maltby scheduled for 10/6 at 9AM.

**Comment by teresaORM** [comment]
Schedule Bogan to trim trees!

**Comment by teresaORM** [comment]
We are on the Bogan waiting list to try to get a trim this year. Call in a while and see where we are on the list/if we can sign up for next year.

**Comment by jcushman** [comment]
Talk to back neighbor

**Comment by teresaORM** [comment]
:deciduous_tree: :evergreen_tree: :deciduous_tree:
