### ISSUE TITLE
Put doors on kitchen cabinets and repaint

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#38]
Either existing ones or new?

Guide to Ikea styles:
http://www.apartmenttherapy.com/which-ikea-kitchen-cabinet-doors-are-best-for-your-design-style-199512

**Comment by teresaORM** [comment]
Actually, I think that guide is out of date. I was thinking something like this, though it wouldn't be super cheap: http://www.ikea.com/us/en/catalog/products/50266361/#/90266359

**Comment by teresaORM** [comment]
Look for doors that exist in basement -- esp for lower cabinets.

**Comment by teresaORM** [comment]
Basement cabinet doors clearly do not belong to these cabinets.

Existing cabinets do not seem to be standard sizes -- we may need to DIY doors for them.

**Comment by teresaORM** [comment]
![image](https://cloud.githubusercontent.com/assets/1180804/10718529/8a805902-7b4b-11e5-8937-04c2c5a286a3.jpg)
![image](https://cloud.githubusercontent.com/assets/1180804/10718530/8a815410-7b4b-11e5-948a-9530f2467f8e.jpg)

**Comment by teresaORM** [comment]
Buy some plywood and hardware?

**Comment by jcushman** [comment]
![image](https://cloud.githubusercontent.com/assets/376272/13029424/0aebea10-d25a-11e5-9205-91bcde55bf71.png)

**Comment by jcushman** [comment]
next to stove: 18" x 22" *2
above stove: 18" x 34" *2
above fridge: 18" x 15.75" *2
right of fridge: 15.25" x 34" *2

**Comment by teresaORM** [comment]
OK, I think this is approximately what I was looking at last time:
Hinges (10 pairs for $20): http://amzn.com/B00CSWEKT0 
Knobs (25 for $25): http://www.ebay.com/itm/25-Amerock-BP53005-G10-Satin-Nickel-Cabinet-Cupboard-Door-Knob-Pull-FREE-SHIP-/161645143379

I believe we have eight new doors and six existing doors (check that), so to replace everything requires 14 pairs of hinges and 14 knobs. We could also decide not to mess with the existing hinges ...

Ordering everything from the same Ebay seller for free shipping:
Same knobs ($1 each): http://www.ebay.com/itm/Amerock-BP53005-G10-Satin-Nickel-Knob-Pull-Cabinet-Cupboard-Door-Drawer-Dresser-/161645143376
Hinges ($1.79 per pair): http://www.ebay.com/itm/Amerock-7139-G10-Cabinet-Hinge-Satin-Nickel-Variable-Overlay-Flush-Mount-PAIR-/201409709365

about $40 for the hardware

**Comment by teresaORM** [comment]
People seem to think Amerock hardware is good for the price:
http://ths.gardenweb.com/discussions/2661928/anyone-have-amerock-or-schaub-hardware

(Also some people buy knobs that cost $10 a piece!)

**Comment by teresaORM** [comment]
Hardware ordered from eBay, estimated delivery 3/22.

**Comment by teresaORM** [comment]
One side done

![img_6667](https://cloud.githubusercontent.com/assets/1180804/14404832/bd4b93bc-fe4d-11e5-8844-96f7a8c5fce5.JPG)

**Comment by teresaORM** [comment]
All doors installed!
