### ISSUE TITLE
Get quote for refinishing floors on first and third floors (and stairs?)

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#49]
- [x] Research some companies to do it
- [ ] Ask about experience with pet smells, whether to just replace some parts, whether removing trim helps, whether slope-y parts can be leveled?

**Comment by jcushman** [comment]
Three top options on Angie's List:

[Taozen Flooring](http://my.angieslist.com/AngiesList/myangie/checkthelist/spinformation.aspx?IEXGL%2b3sCUJawHGIAtHc6Uy2tcbUkBZR3VpGg4fk8X8iGaFPn7M4PRrrCoIqO3ZKjV%2fkEis%2fZZTbIZD3%2b0nPYMvolflfGUhZzs7Qa%2fquMs6J6bs%2b5RH%2ffbjssWv8w6GgrL1irXP0pk7R5O00YT4Z3gisYoVa%2fVe0RKWNaI%2bozAM%3d)
[Phil's Floor Services](http://my.angieslist.com/AngiesList/myangie/checkthelist/spinformation.aspx?2JJm1UAsDefJevoUly8qoP1fgldaFod9nm02fZfFvp%2bHzk%2bgXM%2f2jVjo9DL2aGR0aDTgo1Bk3Kan3DA4AP1Y2lrannUVdBtHehXmgbSG1woybq%2fgNBLLYyiq%2bI761A6%2fCceFLlXMd7oNh3dxUFTgENekVVn1MpgixiD3Gsg1A2o%3d#r11177050)
[Ron Wilson & Sons Hardwood Floors in Mass & NH](http://my.angieslist.com/AngiesList/myangie/checkthelist/spinformation.aspx?IQr%2bwi8SSc6ABv%2butyYCYvJ%2fMADbPpFYIgjASIDkcivTMo7wsAMQ3oAwEr94HbYU%2fx5AgLnTFWKJbwA2mJsZLmQVCkP3a59tgC2aUfwi8TfgcTJ6e8x%2b5JIR5LbKpWs4LqApU0yYPG3zEZvg%2bAo35X9DBDTQcq12XH6At9FaSiM%3d)

**Comment by teresaORM** [comment]
OK, so flooring guys don't answer their phones during the day. (Taozen has a fancy phone system, though.) I sent in requests to arrange estimates via the contact forms on these three sites.

**Comment by teresaORM** [comment]
Wilson and Sons doesn't serve Dorchester.

**Comment by teresaORM** [comment]
Talked to Taozen -- they can come quote on Saturday (will call me back later today to confirm time). (Note that will take 4-5 days to do the sanding/refinishing, we can't live in the house during that time, and all furniture will have to be moved from the area.)

Phil's Floor Services will come to do a quote on Monday, September 21, between 6:30 and 7pm.

**Comment by teresaORM** [comment]
Left message with Taozen to try to confirm Saturday time.

**Comment by teresaORM** [comment]
Taozen will come by at 12pm on 9/12.

**Comment by teresaORM** [comment]
Floors are scheduled. BOOM!
