### ISSUE TITLE
Patch and paint first floor

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#50]
Dining room, living room, hall, and stairs(?). I think this includes
- [ ] wash
- [ ] patch
- [ ] prime
- [ ] paint

Plus picking colors and buying supplies and all that ...

**Comment by jcushman** [comment]
Patch and paint living room/dining room:

- [ ] remove hardware
- [ ] scrape paint
- [ ] mud, caulk, wood putty
- [ ] sand
- [ ] wash
- [ ] tape and tarp
- [ ] prime
  - primer
  - separate alligator primer?
- [ ] paint walls
  - wall paint
- [ ] paint trim
  - trim paint

**Comment by teresaORM** [comment]
Closing as living room and dining room walls are done -- will open separate issues for remaining.

Before:
![livingroombefore](https://cloud.githubusercontent.com/assets/1180804/9983510/7a2286b0-5fcc-11e5-96f6-731444ddac93.JPG)
![diningroombefore](https://cloud.githubusercontent.com/assets/1180804/9983511/7d44db18-5fcc-11e5-8899-43e5a1c27052.JPG)

After:
![livingroomafter](https://cloud.githubusercontent.com/assets/1180804/9983512/8302c768-5fcc-11e5-982d-82977364f0aa.JPG)
![diningroomafter](https://cloud.githubusercontent.com/assets/1180804/9983513/86c227b8-5fcc-11e5-839a-33576574a34b.JPG)
