### ISSUE TITLE
Prime and paint basement stairs

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#51]

**Comment by jcushman** [comment]
Before:

![2015-09-12 14 59 42](https://cloud.githubusercontent.com/assets/376272/9840141/318fe1b6-5a5b-11e5-9a65-d1692bed814a.jpg)
![2015-09-12 14 59 48](https://cloud.githubusercontent.com/assets/376272/9840142/318ff796-5a5b-11e5-9c12-dd4bef5bb3b3.jpg)

During:

![2015-09-12 15 00 02](https://cloud.githubusercontent.com/assets/376272/9840144/385c8c88-5a5b-11e5-8694-e0aed9b6ac2d.jpg)

After:

![2015-09-13 20 25 57](https://cloud.githubusercontent.com/assets/376272/9840148/4373078c-5a5b-11e5-8b80-772322e5c171.jpg)
![2015-09-13 20 49 23](https://cloud.githubusercontent.com/assets/376272/9840147/437068f6-5a5b-11e5-80c0-1e5117013d7d.jpg)

**Comment by teresaORM** [comment]
* Washed stairs
* Primed everything with BIN (and some BIN Advanced on the closet/under stairs)
* Painted just stairs with CalPro 2000 semi-gloss (color Quack Quack)
