### ISSUE TITLE
Add/replace shelves in kitchen cabinets

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#53]
- [ ] Measure sizes
- [ ] See if any of the spare pieces in basement fit or could be cut to fit
- [x] Get some more shelf clips to hold them up

**Comment by teresaORM** [comment]
Check for usable shelves in basement.

**Comment by jcushman** [comment]
Sizes for all shelves:

    * Above-left-right of stove: 19 5/8" *4
    * Above-right of fridge: 32 1/4" *2
    * Above-left of sink: 27 7/8" *2
    * Above-right of sink: 15" * 3

Above fridge needs a new base: 20" x 34.25", plus 2*20" and 1*34" rails of 1.5"x.5"

![image](https://cloud.githubusercontent.com/assets/376272/13029610/0f1e7e90-d25f-11e5-8d97-af0eb684978d.png)

![image](https://cloud.githubusercontent.com/assets/376272/13029612/11810c3e-d25f-11e5-9ad1-3769f3498b7f.png)

![image](https://cloud.githubusercontent.com/assets/376272/13029613/133a35f0-d25f-11e5-81bd-60c20cfb6acc.png)

![image](https://cloud.githubusercontent.com/assets/376272/13029614/14a67bba-d25f-11e5-8923-d58d63f85056.png)

**Comment by teresaORM** [comment]
Before
![image](https://cloud.githubusercontent.com/assets/1180804/13554264/7b42c7a2-e371-11e5-8680-93ead18aaf4d.jpeg)
![image](https://cloud.githubusercontent.com/assets/1180804/13554265/7b544fa4-e371-11e5-9894-3a8628c60980.jpeg)
![image](https://cloud.githubusercontent.com/assets/1180804/13554266/7b571e82-e371-11e5-8178-288bbf5bbef3.jpeg)
![image](https://cloud.githubusercontent.com/assets/1180804/13554267/7b583772-e371-11e5-8526-3a1baa36fba6.jpeg)

**Comment by teresaORM** [comment]
After
![image](https://cloud.githubusercontent.com/assets/1180804/13554270/983d1524-e371-11e5-82e5-5797532315ea.jpeg)
![image](https://cloud.githubusercontent.com/assets/1180804/13554271/9848af42-e371-11e5-8ebd-a2343792c3ed.jpeg)
![image](https://cloud.githubusercontent.com/assets/1180804/13554272/984ba7ba-e371-11e5-99df-aec2d5e1b6af.jpeg)
