### ISSUE TITLE
Paint bathroom

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#57]
* [X] [remove wallpaper](http://www.familyhandyman.com/walls/the-best-way-to-remove-wallpaper/view-all)
* [X] patch holes
  * DAP Fast Patch Patching Compound Powder
* [X] re-attach trim
  * 1-1/4-in. drywall nails
  * finish screws
* [X] caulk cracks
  * latex caulk, 1 tube
* [X] sand, re-mud
  * 120-grit drywall sandpaper
* [X] tape off non-painted areas
* [X] prime
  * white BIN shellac
* [X] paint
  * Glidden Duo semi-gloss swan white
* [x] re-attach fixtures

**Comment by teresaORM** [comment]
To track your paint rebate: https://www.homedepotrebates.com/paperless/akzonobel/track.html
Tracking number: 695665889

**Comment by jcushman** [comment]
Removing wallpaper:

![img_5439](https://cloud.githubusercontent.com/assets/376272/9722669/2f280ab0-557f-11e5-92d4-31faac52eef9.JPG)
![img_5441](https://cloud.githubusercontent.com/assets/376272/9722667/2b80fae8-557f-11e5-82ae-580094edc0f3.JPG)

Wallpaper removed:

![2015-09-05 12 21 46](https://cloud.githubusercontent.com/assets/376272/9722650/d0c13faa-557e-11e5-9843-8f12b1d00a50.jpg)

Sanding:

![2015-09-06 20 43 49](https://cloud.githubusercontent.com/assets/376272/9722651/d5d02d44-557e-11e5-836b-320168a4b531.jpg)

**Comment by teresaORM** [comment]
SUCCESS!
