### ISSUE TITLE
Check wifi coverage throughout house

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#60]
Using Teresa's laptop?

**Comment by teresaORM** [comment]
I used http://www.speedtest.net/

### first floor
front hall: 87.83 Mbps down / 6.03 Mbps up
kitchen: 87.94/6.02
dining room: 87.64/6.04
living room: 80.43/6.06

### second floor
back bedroom: 79.17/6.03
blue bedroom: 88.20/6.03
bathroom(?!?): 87.50/6.00
front bedroom: 87.81/5.61
front office/cat room: 88.14/5.99

### third floor
front room: 88.07/6.02
back room: 73.40/5.99
bathroom (?!?): 82.49/6.04

**Comment by teresaORM** [comment]
OK to close this up, or do you want to try tweaking anything, @jcushman?

**Comment by jcushman** [comment]
Those numbers look great to me! Fancy router FTW.
