### ISSUE TITLE
Home heating system

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#63]
Let's have one!

**Comment by jcushman** [comment]
Calls:

Sila Heating & Air Conditioning - scheduled estimate 9/28 at 9AM. (furnace & hot water)
Coastal Heating & Air Conditioning - 9/29 at 9AM. (heat only)
Boston Standard Co - waiting for call back.

**Comment by jcushman** [comment]
Boston Standard Co - 9/30 at 8AM (heat and hot water)

**Comment by jcushman** [comment]
Replacement scheduled for 11/23.

**Comment by teresaORM** [comment]
![image](https://cloud.githubusercontent.com/assets/1180804/11452724/176665bc-95c0-11e5-8ce9-d56b5982a0aa.jpg)
