### ISSUE TITLE
Switch bathroom doorknob hardware with closet

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#69]
Model: Corbin 770

**Comment by jcushman** [comment]
![2015-09-11 19 25 31](https://cloud.githubusercontent.com/assets/376272/9840199/356ebac2-5a5c-11e5-9774-f530c1a806b2.jpg)

**Comment by teresaORM** [comment]
Swap hardware with closet instead.

**Comment by jcushman** [comment]
Done! Also fixed the spring.
