### ISSUE TITLE
Replace trim above door in entryway

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#72]
Need 1x4 board, 4'9"

**Comment by teresaORM** [comment]
![img_5496](https://cloud.githubusercontent.com/assets/1180804/9840218/82293e8c-5a5c-11e5-97e0-1e1e017f26d7.JPG)

**Comment by teresaORM** [comment]
Trimmed!

![img_5619](https://cloud.githubusercontent.com/assets/1180804/10221265/558c456e-681b-11e5-8133-13aba036e8f7.JPG)
