### ISSUE TITLE
Rack for hanging mops/brooms in basement stairs

### ISSUE THREAD

**Issue by teresaORM** [jcushman/house#73]
I was originally thinking something like this:
http://amzn.com/B00S75VYR8

But I think these might appeal to you, @jcushman. Could use some for organizing tools in the basement, too:
http://amzn.com/B00GP59R0S

**Comment by jcushman** [comment]
Yeah, looks like those could be handy! Maybe a bit tricky to attach, but worth a try ...

**Comment by teresaORM** [comment]
OK, ordered some!

**Comment by teresaORM** [comment]
Racked!

![img_5654](https://cloud.githubusercontent.com/assets/1180804/10356212/b669c844-6d42-11e5-9fa5-85a4c47d4143.JPG)
