### ISSUE TITLE
Clean mildew from siding

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#76]
This one might be DIY if we can reach? 

http://www.buffalo-lumber.com/lumber-articles/how-to-clean-mold-off-cedar-siding.htm

**Comment by jcushman** [comment]
And/or http://m.homedepot.com/p/Mold-Armor-56-oz-House-Wash-Hose-End-Sprayer-FG511/100625157

**Comment by teresaORM** [comment]
Seems worth trying! People are excited about the Mold Armor, but it seems like mostly for vinyl siding?

**Comment by teresaORM** [comment]
Done for now!
