### ISSUE TITLE
Wash chandeliers 

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#8]
- [x] front hall
- [x] front bedroom
- [x] kitchen
- [x] dining room
- [x] blue bedroom
- [x] back bedroom

**Comment by teresaORM** [comment]
Waiting on a ladder.

http://www.apartmenttherapy.com/how-to-clean-a-crystal-chandel-42952

**Comment by teresaORM** [comment]
Not by any means quick!

- [x] front hall
- [x] front bedroom

![img_5412](https://cloud.githubusercontent.com/assets/1180804/9594885/5c61d8bc-502f-11e5-8aad-b0722ab40988.JPG)
![img_5419](https://cloud.githubusercontent.com/assets/1180804/9594888/5ff94cc6-502f-11e5-929a-c984d2b18348.JPG)

- [ ] kitchen
- [ ] dining room
- [ ] blue bedroom
- [ ] back bedroom
- [ ] others??

**Comment by teresaORM** [comment]
Fixed the bulb that wasn't lighting in the kitchen by vacuuming a bunch of dead flies out of the socket. +1 shopvac!

**Comment by teresaORM** [comment]
Back bedroom cleaned!

![img_5447](https://cloud.githubusercontent.com/assets/1180804/9704480/7eb2a8ec-5476-11e5-8a32-7e396064fa1a.JPG)
