### ISSUE TITLE
Paint dining room windows/doors and trim

### ISSUE THREAD

**Issue by teresaelsey** [jcushman/house#83]
Consider encapsulating?
http://www.mass.gov/eohhs/gov/departments/dph/programs/environmental-health/exposure-topics/lead/delead/faq/what-is-encapsulation.html

**Comment by jcushman** [comment]
Here's a contractor offering moderate risk deleading:

http://www.homeadvisor.com/rated.SupremeConstruction.2184841.html

Our areas marked loose: dining room door, sun room window sills, doors in 3rd floor back room, basement windows, front door threshold.

**Comment by teresaORM** [comment]
Remove dining room door, lead-test surfaces, paint/encapsulate?

**Comment by teresaelsey** [comment]
Befores:
![img_8341](https://user-images.githubusercontent.com/1180804/41798643-68385054-763c-11e8-98b6-c80dbc40aa13.JPG)
![img_8340](https://user-images.githubusercontent.com/1180804/41798644-68454d04-763c-11e8-8d92-eaeb1724f960.JPG)
![img_8336](https://user-images.githubusercontent.com/1180804/41798645-6878163a-763c-11e8-9041-435916cbfbd3.JPG)
![img_8335](https://user-images.githubusercontent.com/1180804/41798646-6886605a-763c-11e8-8a85-a4af8a772959.JPG)
![img_8334](https://user-images.githubusercontent.com/1180804/41798647-689571e4-763c-11e8-9fa4-27599a0c83e4.JPG)
