### ISSUE TITLE
Patch tub enamel

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#86]
Maybe Dresden blue? I'm not sure if this is the right product, but it has a good color chart: https://www.historichouseparts.com/pdshop/shop/item.aspx?itemid=9910

**Comment by jcushman** [comment]
Ordered turquoise ceramifix.

**Comment by teresaORM** [comment]
Before
![image](https://cloud.githubusercontent.com/assets/1180804/13030108/6f145488-d26d-11e5-8bfc-4330fae5fe65.jpeg)
![image](https://cloud.githubusercontent.com/assets/1180804/13030109/6f23814c-d26d-11e5-8562-125c50c00eb5.jpeg)

**Comment by teresaORM** [comment]
After
![image](https://cloud.githubusercontent.com/assets/1180804/13030111/7fbd9cd6-d26d-11e5-9eb6-ba6b32e8abd1.jpeg)
